import type { NextPage } from 'next';
import Head from 'next/head';
import React, { Component } from "react";
// import styles from '../styles/Home.module.css';
import Header from '../component/Header';
import Navbar from '../component/Navbar';
import SlideShow from '../component/SlideShow';
import SwiperSlideShow from '../component/SwiperSlideShow';
import LatestNotice from '../component/LatestNotice';
import SchoolHistory from '../component/SchoolHistory';
import NoticeBoard from '../component/NoticeBoard';
import StudentAttendance from '../component/StudentAttendance';
import HeadTeacher from '../component/HeadTeacher';
import Gallery from '../component/Gallery';
import Footer from '../component/Footer'; 


const Home: NextPage = () => {
	
	const stop = () => {
	}
	const start = () => {
	}

	return (
		<>
			<Head>
				<title>Sotrajit High School</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<Navbar />

			<SlideShow />

			<SwiperSlideShow/>

			<LatestNotice />

			{/* স্কুল ইতিহাস */}
			<SchoolHistory/>
			
			<NoticeBoard/>

			{/* শিক্ষার্থীদের উপস্থিতি */}
			<StudentAttendance/>


			{/* প্রধান শিক্ষকের বানী */}
			<HeadTeacher/>


			{/* গ্যালারি */}
			<Gallery/>

			<Footer/>

		</>
	)
}

export default Home
